### ISSUE TITLE
Better settings validation and security

### ISSUE THREAD

**Issue by guillaumemolter** [wildbit/postmark-wordpress#12]
Settings from the admin form should be properly validated instead of "blindly trusting" values returned by the form. 

The form should also use a [nonce](https://codex.wordpress.org/WordPress_Nonces) for enhanced security.

We should also check that the user [has sufficient privilege](https://codex.wordpress.org/Function_Reference/current_user_can) to update the settings.

**Comment by cfoellmann** [comment]
This is done.

CLOSE
