### ISSUE TITLE
load_settings() does not exist?

### ISSUE THREAD

**Issue by mgibbs189** [wildbit/postmark-wordpress#39]
Hey @pgraham3 

I noticed this addition in a recent commit: https://github.com/wildbit/postmark-wordpress/blob/5aefc0f4f54c112b307c05fe8eb5ca961a9bb05a/postmark.php#L386

Has this change been tested?

I ask because `load_settings` is `Postmark_Mail` class method, but does **not** appear to be a global function.

**Comment by pgraham3** [comment]
v1.11.1 just released with a fix.

**Comment by mgibbs189** [comment]
@pgraham3 Great! Thanks for the quick turnaround :)
