### ISSUE TITLE
Allow "From" header to override the default sender.

### ISSUE THREAD

**Issue by atheken** [wildbit/postmark-wordpress#4]
Allow users to include a "From" header in mail they send using the wp_mail function. This would override the default sender configured in the control panel. (The sender would still need to be a confirmed sender signature...)

**Comment by mgibbs189** [comment]
What happens if they try using a `From` address that isn't a confirmed sender?

**Comment by atheken** [comment]
@mgibbs189 the Postmark API will produce an API [Error code, 401](http://developer.postmarkapp.com/developer-api-overview.html#error-codes). This error can also occur if a user has configured the default sender, and then removes it from their account at a later time.

BTW, I really just opened this as a reminder to enhance the plugin, no expectation for you to update the plugin, but your contributions are great and much appreciated, if you want to take it on.

**Comment by mgibbs189** [comment]
No worries. Been loving Postmark thus far, so I'll do whatever I can to help.

**Comment by atheken** [comment]
This is done as of version 1.9 of the plugin.
