### ISSUE TITLE
GitHub vs WP.org

### ISSUE THREAD

**Issue by cfoellmann** [wildbit/postmark-wordpress#43]
MAJOR ISSUE:
I just tried to contribute to the codebase by checking out the repo here on GitHub.
When I activated tagged version 1.11.2 (gh) in my dev install it took me some time to realize that the version is broken.
The code differs from the released version on wp.org!
e.g. link tracking can not be activated because the js file is missing the code to hand the setting over to the ajax request.

Please update the repo with the current release code.
I am ready to put my work, time and energy into this project and my money in the service. If the plugin can not close the gap to the fantastic service/webUI I need to move on to a rival service.

**Comment by pgraham3** [comment]
@cfoellmann I updated the Github repo assets to match the current assets in the SVN repo:

https://github.com/wildbit/postmark-wordpress/releases/tag/v1.11.2

Thanks for the heads up.
