### ISSUE TITLE
POSTMARK_DIR is undefined when upgrading plugin via CLI

### ISSUE THREAD

**Issue by pgraham3** [wildbit/postmark-wordpress#58]
https://wordpress.org/support/topic/upgrade_completed-method-uses-undefined-postmark_dir-constant/

> 
> If you upgrade any other plugin via the CLI (wp plugin upgrade), you get a warning from Postmark that POSTMARK_DIR is undefined, as it’s called via a filter, and isn’t initialized.
> 
> Can this be addressed?
> 
> Warning: Use of undefined constant POSTMARK_DIR – assumed ‘POSTMARK_DIR’ (this will throw an Error in a future version of PHP) in /app/wp-content/plugins/postmark-approved-wordpress-plugin/postmark.php on line 450

**Comment by pgraham3** [comment]
@broksonic21 Just release v1.12.5 - please let me know if you see the undefined POSTMARK_DIR warning the next time you upgrade other plugins via the CLI. I switched to using [plugin_basename](https://developer.wordpress.org/reference/functions/plugin_basename/) to get the Postmark plugin when doing the comparison to the upgraded plugins, instead of using the constant + filename concatenated string.

**Comment by broksonic21** [comment]
This worked fine - Thanks!
