### ISSUE TITLE
Disable REST API email sending programatically

### ISSUE THREAD

**Issue by pderksen** [wildbit/postmark-wordpress#6]
Is there a way to disable sending emails via the REST API through code?

In my case, when I make a snapshot of my live site to staging (in this case WP Engine), I can then detect I'm on a staging URL, and send automated emails through the site to a test SMTP server (in this case mailtrap.io).

If I forget this then user accounts on my site will start to get automated emails through the staging site (purchase renewal reminders, etc).

If there was simply a way to disable sending emails with this plugin (like unchecking the "Enable" checkbox in the settings does) without having to deactivate the entire plugin that would be ideal.

Thanks!

**Comment by mgibbs189** [comment]
Hi @pderksen 

Not currently, but we could probably add a filter to [this line](https://github.com/wildbit/postmark-wordpress/blob/a7b31e9e2a2856afdb127ed9fc740413a67e0ea6/postmark.php#L112).

Before:

```php
if ( 1 == $postmark->settings['enabled'] ) {
```

After:

```php
$enabled = (bool) $postmark->settings['enabled'];
if ( apply_filters( 'postmark_enabled', $enabled ) ) {
```

Usage:

```php
add_filter( 'postmark_enabled', '__return_true' );
```

**Comment by mgibbs189** [comment]
See #7

**Comment by pderksen** [comment]
@mgibbs189 That should do it. Pretty straight-forward. Thanks!

**Comment by atheken** [comment]
Thanks @mgibbs189! I merged it to master.

@pderksen Feel free to grab the latest from master, or you might also use our "testing" key for sending from staging, `POSTMARK_API_TEST`, as outlined here: http://developer.postmarkapp.com/developer-send-api.html
