### ISSUE TITLE
Add Message Stream Support

### ISSUE THREAD

**Issue by gvenk** [wildbit/postmark-wordpress#73]
I saw there is support for [Message Stream in the Craft CMS plugin](https://postmarkapp.com/blog/how-to-reliably-deliver-craft-email-with-the-postmark-plugin), are there any plans to add this also to the WordPress plugin?

**Comment by pgraham3** [comment]
Hi, @gvenk! 

You can currently set a message stream to use in the Postmark for WordPress plugin settings:

![Screen Shot 2021-03-03 at 9 07 22 AM](https://user-images.githubusercontent.com/16660335/109843452-eb549d00-7bff-11eb-9d92-50aa423f1d0a.png)

The default used is 'outbound' which is for the default server transactional stream. You can change that to a different stream you want to use though it is a single stream setting per site.

Are you asking for support for setting a message stream via headers or some other method at the message level?

**Comment by gvenk** [comment]
Ah, great, I hadn't noticed this. I'm gonna try it, thanks!
