### ISSUE TITLE
Allow configurable timeout for DNS lookups.

### ISSUE THREAD

**Issue by atheken** [wildbit/postmark-wordpress#8]
Investigate options for allowing longer DNS lookup windows.

From user report:

"I looked at the result of the $response request in postmark.../wp-mail.php and got this error:

wp-error - http request error - name lookup timed out.

It appears my dns was a bit slow. So I looked up the docs of the wp_remote_post function and added a timeout option to the $args array and that fixed it."

**Comment by mgibbs189** [comment]
@atheken The WP_Http library already has hooks to control timeouts. I don't think this warrants its own UI settings since it's an edge case.

E.g. the `http_request_args` and `http_request_timeout` filters
